name: ecommerce
description: Infra for the DTD Nestjs course ecommerce backend
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
